version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diploma
    ports:
      - 3306:3306
    networks:
      - backend
      - frontend
  app-server:
    image: server-app
    build:
      context: ./DiplomaServer/
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./resources:/resources
    networks:
      - backend
  app-client:
    image: client-app
    build:
      context: ./Diploma/
      dockerfile: Dockerfile
    ports:
      - 80:4200
    networks:
      - frontend

networks:
  backend:
  frontend:
